package mapping;

// Generated 8 f�vr. 2015 15:44:33 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Pharmacie generated by hbm2java
 */
@Entity
@Table(name = "pharmacie", catalog = "pharmacie")
public class Pharmacie implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String nom;
	private String tel;
	private String adresse;
	private boolean garde;

	public Pharmacie() {
	}

	public Pharmacie(String nom, String tel, String adresse, boolean garde) {
		this.nom = nom;
		this.tel = tel;
		this.adresse = adresse;
		this.garde = garde;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nom", nullable = false, length = 254)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "tel", nullable = false, length = 254)
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	@Column(name = "adresse", nullable = false, length = 254)
	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	@Column(name = "garde", nullable = false)
	public boolean isGarde() {
		return this.garde;
	}

	public void setGarde(boolean garde) {
		this.garde = garde;
	}

}
